### ISSUE TITLE
Use "index.html" as the filename of the spec.

### ISSUE THREAD

**Issue by AFBarstow** [w3c/FileAPI#1]
A common practice when the gh-pages (branch) is used, is to name the main file "index.html". Unless there's a good reason to keep with "Overview.html", please use "index.html" instead.

**Comment by shepazu** [comment]
Agreed. "Overview.html" is no more descriptive of a spec file than "index.html". I think it's just an outmoded early convention W3C used.

**Comment by WebAppsWG** [comment]
This was fixed in https://github.com/w3c/FileAPI/commit/bd64936629e4deb5b566d009f5cd2b731ce280f0
