### ISSUE TITLE
Include MediaSource overload for createObjectURL

### ISSUE THREAD

**Issue by saschanaz** [w3c/FileAPI#100]
Currently [the MSE spec](https://github.com/w3c/media-source/issues/211) adds overload for createObjectURL using partial interface, but [the Web IDL spec says](https://heycam.github.io/webidl/#idl-overloading):

>Operations must not be overloaded across interface, partial interface, interface mixin, and partial interface mixin definitions.

We should directly include the overload in the original definition.

**Comment by annevk** [comment]
Another reason this is a good idea is that we don't really want to spread this pattern further. It's incredibly leaky and error-prone.
