### ISSUE TITLE
Implementer interest in this spec

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/FileAPI#111]
Wondering which browsers have committed to implementing this specification?

This is to help us determine if we keep this in the Charter or if we move this spec to the WICG.

**Comment by marcoscaceres** [comment]
I'm being told that this specification represents what is interoperable across browsers and that new things moved to https://wicg.github.io/entries-api/

Is that correct? If so, it would be great to update the SoTD or Abstract to reflect the above.

**Comment by marcoscaceres** [comment]
Just to be clear what the spec represents.

**Comment by annevk** [comment]
I guess I don't really understand, it seems to have a pretty clear Abstract et al, albeit a tad verbose.

**Comment by marcoscaceres** [comment]
Respectfully, I disagree. Otherwise, I would not have filed the issue.

**Comment by marcoscaceres** [comment]
To be clear, this issue arose because none of the WG chairs could determine the status or level of interest in this spec. I can appreciate that people involved in the spec might know the status, but it’s unclear to external parties.

**Comment by marcoscaceres** [comment]
Alternatively is the addition of an implementation report, given that there is a test suite. That would really help.

**Comment by annevk** [comment]
Since when is any of those part of the Abstract or SotD though?

**Comment by marcoscaceres** [comment]
Argh, Anne. Stop.

**Comment by marcoscaceres** [comment]
The implementation report is fairly standard at the top of a spec.

**Comment by inexorabletash** [comment]
> I'm being told that this specification represents what is interoperable across browsers and that new things moved to https://wicg.github.io/entries-api/

Entries-API itself should probably not exist; it documents some _de facto_ standards but the contents should really be merged into FileAPI and HTML.

**Comment by inexorabletash** [comment]
> Wondering which browsers have committed to implementing this specification?

"All of them" ? The four major engines all support nearly all of the spec, albeit with some interop issues: https://wpt.fyi/results/FileAPI?label=stable&aligned=true

**Comment by marcoscaceres** [comment]
> Entries-API itself should probably not exist; it documents some de facto standards but the contents should really be merged into FileAPI and HTML.
 
ok, that’s really useful to know. Maybe we can look at what needs to go into both and start bringing stuff back from entries into this spec. 

Also, it would be awesome to have the wpt.fyi link serve as the implementation report link. Helps us easily track status.

**Comment by marcoscaceres** [comment]
Closed via #112
