### ISSUE TITLE
Consider dropping lowercasing requirement for the type attribute

### ISSUE THREAD

**Issue by wisniewskit** [w3c/FileAPI#122]
While working on Gecko's Fetch compliance, I noted that there are web platform tests which do not expect blob types to be lowercased. @annevk suggested that dropping the lowercasing requirement might be an option, so I'm filing a bug to verify that option.

**Comment by annevk** [comment]
To elaborate a tiny bit, [parse a MIME type](https://mimesniff.spec.whatwg.org/#parse-a-mime-type) already lowercases the type, subtype, and parameter names, but lowercasing parameter values technically makes us lose information, so shouldn't be done.

**Comment by annevk** [comment]
This will probably fall out of #123.

**Comment by annevk** [comment]
Let's duplicate this into #43.
