### ISSUE TITLE
[FileAPI] WebAppsWG TPAC F2F agenda (Fukuoka, Sep 19-20 2019)

### ISSUE THREAD

**Issue by dmurph** [w3c/FileAPI#137]
**draft** of things to talk about at TPAC about FileAPI

### Problem
The File API specification has accumulated quite a few open issues, some of which are really old. Link: https://github.com/w3c/FileAPI/issues/

### Proposal
We would like to have the community help us decide which issues are worth considering, and which issues can be closed.

**Comment by dmurph** [comment]
Attaching to w3c/webappswg#10

**Comment by mkruisselbrink** [comment]
One particular thing I'd like to discuss is what to do about the "type" property. I.e. issues #13, #43, #123 (although maybe there isn't actually much to discuss there, and it just requires somebody to finish writing the spec text).

**Comment by annevk** [comment]
Yeah, I really hope the conclusion for the `type` attribute is none other than update implementations to use the MIME type parser and serializer.

**Comment by annevk** [comment]
My top issues would be scope of the blob store and same-origin policy checks for blob fetching.
