### ISSUE TITLE
Specification status report for TPAC 2019

### ISSUE THREAD

**Issue by LJWatson** [w3c/FileAPI#138]
Please can you respond to this comment with a brief specifications status report for the WebApps meeting at TPAC. The report should address the following:
* What progress has your spec made in the last 12 months?
* Is anything blocking your spec from moving to CR?
* If yes, what is your plan to unblock it and do you need any help?
* What do you want to achieve for your spec in the next two days (of breakout sessions)?

We're tracking these status reports in [WebApps issue #19](https://github.com/w3c/webappswg/issues/19)

Thanks.

**Comment by siusin** [comment]
see #137

**Comment by mkruisselbrink** [comment]
> Please can you respond to this comment with a brief specifications status report for the WebApps meeting at TPAC. The report should address the following:
> 
> * What progress has your spec made in the last 12 months?

Added some convenience read methods to `Blob` (`Blob.text()`, `Blob.arrayBuffer()` and `Blob.stream()`), and cleaned up some of the spec text around the FileReader API.

> * Is anything blocking your spec from moving to CR?

(not entirely sure what consequences are from moving to CR, but) there is a bunch of work left cleaning up the spec text, particularly around `Blob.type`. And it would be nice to get feature requests such as #140 in as well. Other than that I think the spec is fairly stable and I don't anticipate any major changes.

> * If yes, what is your plan to unblock it and do you need any help?
> * What do you want to achieve for your spec in the next two days (of breakout sessions)?

See also #137. Mainly go through open issues and figure 

> 
> We're tracking these status reports in [WebApps issue #19](https://github.com/w3c/webappswg/issues/19)
> 
> Thanks.

**Comment by marcoscaceres** [comment]
Ok, let us know when #140 is done and the other changes are made and we can start the transition process to CR. Feel free to close this bug and thanks again for the status update!
