### ISSUE TITLE
.msg MimeType Not Recognized

### ISSUE THREAD

**Issue by jensenma** [w3c/FileAPI#15]
It appears that in certain instances the FileAPI is not recognizing the MIME type for .msg (Microsoft Outlook) files.  This is a worldwide standard no different from a .jpg or .png file so why would it not be recognized.  Specifically we are using the RadAsyncUpload control from Telerik which I understand is built upon the File API but the content type (Mime Type) for those files is not being passed back via the control presumably because the FileAPI is not recognizing it.  Added the Mime type to local registry or IIS server has no effect.  Please provide guidance and/or fix.

**Comment by inexorabletash** [comment]
The FileAPI spec does not define MIME types, sniffing content, or associating extensions with types. That's up to the user agent and/or operating system. (e.g. on Windows it's done by the registry plus whatever extra smarts the browser has).

Closing as "out of scope"
