### ISSUE TITLE
features request:add SynFileReader for Avoid Callback Hell Programming from FileReader

### ISSUE THREAD

**Issue by annopnod** [w3c/FileAPI#162]
Avoid Callback Hell Programming from FileReader

SynFileReader
var file=new SynFileReader("test.json");
file.write("test");
file.seek(1000);
console.log(file.pointer);//return 1000
console.log(file.length());
console.log(file.read(1024));

**Comment by annevk** [comment]
This already exists in workers, it's called `FileReaderSync`. It won't be exposed elsewhere as it's bad for users to have non-responsive applications.
