### ISSUE TITLE
Remove FileList (Migrate to | typedef FileList FrozenArray<File>; |

### ISSUE THREAD

**Issue by arunranga** [w3c/FileAPI#19]
This is https://www.w3.org/Bugs/Public/show_bug.cgi?id=24586 which I'm migrating over. Currently, FileList is an interface in WebIDL; this bug is to make it a FrozenArray. Some other discussions (including the Directory Upload discussion) will affect this bug.

**Comment by jimmywarting** [comment]
Why should it be a frozen array? Why can't we push in a `new File([], "name.txt")` or drop a "to large file" in a `<input type=file>`

**Comment by Alex-Code** [comment]
As above, Would be nice to be able to modify a file that has been selected (Client side image resizing).

**Comment by jimmywarting** [comment]
...ping

**Comment by jimmywarting** [comment]
I would have hope something would have change in one year. But it's still the same 😞

**Comment by vsesh** [comment]
@jimmywarting What type of object you are talking about?

**Comment by jimmywarting** [comment]
@vsesh 
It's a same that you can't modify the file list
I wouldn't want `input.files` to be a FrozenArray

I want to take a file, modify it, reconstruct a new File object and push it into `input.files` but that wouldn't be possible if it's going to be a frozen array

**Comment by vsesh** [comment]
@jimmywarting 
I understand, but now JS hasn't typed array (<T>Array like C#). TypedArray of with any type. Only for primitive types like int, long and another.

**Comment by annevk** [comment]
I'm going to close this since I don't think it's worth the churn. Making `FileList` constructable might be worth considering as part of #24.
