### ISSUE TITLE
Allow Blob constructor to take ownership of ArrayBuffer(View) / invoke DetachArrayBuffer

### ISSUE THREAD

**Issue by arunranga** [w3c/FileAPI#23]
We should do this in the Blob constructor. Per Jonas Sicking, something like this:

"new Blob([myArrayBuffer], { transfer: [myArrayBuffer] });
and
new File([otherBuffer], "myFile", { transfer: [otherBuffer] });"

would work quite well I think.

This might syntactically resemble transferList from postMessage.

**Comment by annevk** [comment]
Let's close this given that there haven't been a lot of requests for this functionality.

**Comment by jimmywarting** [comment]
I where just about going to ask about this functionality...
