### ISSUE TITLE
Add a FileList.drop(index) method

### ISSUE THREAD

**Issue by dmoagx** [w3c/FileAPI#25]
Migrating my own request https://www.w3.org/Bugs/Public/show_bug.cgi?id=17125 :

Currently a FileList provided by a file input element is readonly.

This is problematic if the user added multiple files to a file list and then sees that he included one file too much and want's to remove it before uploading the files. Right now he has to start his selection from scratch. 

If there was a way to drop items from a FileList some JavaScript could display a list of selected files and allow to remove items one-by-one.

Duplicate https://www.w3.org/Bugs/Public/show_bug.cgi?id=16834 adds another use case:
- Checking the file.size for some limit before uploading, if limit is exceeded exclude the particular file from uploading.

#24 discusses an alternative approach, fitting a wider range of use cases.

**Comment by arunranga** [comment]
@dmoagx: thought I'd point out a few things:

1. FileList itself may become an Array or at least Array-like. Hopefully, this would make something like drop(index) unnecessary.
2. We intend to introduce directory-picking on the platform. That is, the standard file picker on Mac OS X will have additional options to pick a directory, which you can submit along with path using a standard form upload. This API is WICG/directory-upload (https://wicg.github.io/directory-upload/proposal.html). When users select directory picking, the FileList is null.

So: I think 1 is the right approach for your feature. But for 2. we'll need to think about use cases more carefully.

**Comment by vsesh** [comment]
#19

**Comment by inexorabletash** [comment]
Note that this can be done using the [FormData](https://xhr.spec.whatwg.org/#interface-formdata) interface. Given a form such as:

```html
<form id=f>
  <input name=fs type=files multiple>
</form>
```

* Create a FormData populated with the form:
   `fd = new FormData(document.getElementById('f'))`
* Get an array of the files:
   `files = fd.getAll('fs')`
* Remove from the FormData:
  `fs.delete('fs')`
* Filter the files:
   `files = files.filter(file => ...)`
* Assign back to the FormData:
   `files.forEach(file => fd.append('fs', file))`
* Submit the FormData via [fetch](https://fetch.spec.whatwg.org/) or [XHR](https://xhr.spec.whatwg.org)

**Comment by annevk** [comment]
Given that there's an alternative and a better proposal in #24, let's close this. If there's a library in widespread usage that enable this we can reconsider.
