### ISSUE TITLE
Include file creation time and last access time.

### ISSUE THREAD

**Issue by mintern** [w3c/FileAPI#26]
Right now, the `File` includes a `long long lastModified`. Is there any possibility of adding creation and last access times as well?

**Comment by annevk** [comment]
Given that there haven't been a lot of requests for this functionality and it would expose more than end users might want to expose about their files, let's close this.

**Comment by jimmywarting** [comment]
currently building some file system hierarchy that could benefit from this information... a bit chocked that not more ppl have bumped this thread and gave it some more 👍  after 7 years
