### ISSUE TITLE
Define cloning of Blob and FileList objects inline

### ISSUE THREAD

**Issue by annevk** [w3c/FileAPI#32]
Once https://github.com/whatwg/html/pull/727 lands the HTML Standard will contain a monkey patch that should move here.

**Comment by domenic** [comment]
To be clear, the intention is that Files are not cloneable, but Blobs are? HTML currently does not define e.g. that the name or lastModified should be cloned over.

**Comment by domenic** [comment]
BTW this is changing as part of https://github.com/whatwg/html/pull/2421, so please don't upstream yet, although reviewing the work done there would be good.

**Comment by mkruisselbrink** [comment]
I believe both should be cloneable (after all cloning FileLists relies on being able to clone Files), but yeah, the current language in the HTML spec does seem a bit unclear (I also haven't actually verified how current browser deal with cloning of File objects). I assumed "the same underlying data" would include the name and lastModified for File objects.

**Comment by domenic** [comment]
Hmm OK, I'll flesh out the patch in the update being done as part of https://github.com/whatwg/html/pull/2421 in that case.
