### ISSUE TITLE
Use `optional` for the Blob constructor

### ISSUE THREAD

**Issue by Ms2ger** [w3c/FileAPI#33]
Currently, the spec has (boring parts omitted):
```
[Constructor, Constructor(sequence<...> blobParts, optional BlobPropertyBag options)] 
interface Blob {
```
It would probably be better to use
```
[Constructor(optional sequence<...> blobParts, optional BlobPropertyBag options)] 
interface Blob {
```

Note that this handles
```js
new Blob(undefined)
```
differently: the current spec throws a `TypeError`; after the change, it would be equivalent to `new Blob()`.

CC @bzbarsky

**Comment by bzbarsky** [comment]
I don't have strong views on how this should work, but yeah, the only difference I can think of is in how `new  Blob(undefined)` is handled.  At least that's the case as long as we don't add more overloads of the constructor.

**Comment by annevk** [comment]
This is part of the reason why we should avoid overloads I think. `new Blob(undefined)` not being `new Blob()` is weird and we should fix that here. (We cannot change it at the IDL-level unfortunately as that would break XMLHttpRequest, though if that's the only case maybe we should fix that specially somehow?)
