### ISSUE TITLE
Store HTTPS state on Blob objects

### ISSUE THREAD

**Issue by annevk** [w3c/FileAPI#35]
See https://github.com/whatwg/html/issues/929 for details.

**Comment by mikewest** [comment]
Note that this will solve at least one source of CSP bypasses (request data from the web, put it into a blob, then `window.open` the blob). It's something I'm interested in doing for Chrome, I just haven't taken time yet.

**Comment by annevk** [comment]
Perhaps #142 is a better solution here as you could always retrieve the bytes from a `Blob` object and put them in another `Blob` object to circumvent this strategy.

**Comment by annevk** [comment]
We achieved an even better solution, removal of HTTPS state: https://github.com/whatwg/fetch/pull/1067.
