### ISSUE TITLE
Re-add FileReader.readAsBinaryString() ?

### ISSUE THREAD

**Issue by inexorabletash** [w3c/FileAPI#39]
Stats in Chrome: https://www.chromestatus.com/metrics/feature/timeline/popularity/814

Hovering around 0.0008% which is low. But an HTTPArchive search turned up thousands of uses; spot-checking, it's not just one library but several different uses. The method is implemented in Edge, FF,  Chrome and Safari.

So... is it worth continuing to try and drop it from implementations, or should we just accept it as a wart on FileReader, document, and move on?

(As an aside, cribbing `text()` and `arrayBuffer()` from Body to Blob would be awesome...)

**Comment by annevk** [comment]
If it's implemented everywhere, yes, add it back. Not worth worrying about it.

Separate issue for `text()` and `arrayBuffer()`?

**Comment by gsnedders** [comment]
Note Edge implemented it after it was dropped from the spec.
