### ISSUE TITLE
Bikeshedding the spec

### ISSUE THREAD

**Issue by tabatkins** [w3c/FileAPI#5]
In [my fork](https://github.com/tabatkins/FileAPI), I'm converting the spec to the Bikeshed processor.  The current generated file is pretty inaccurate in several places - it's clear that the ToC has drifted from the actual sections over time, for example.

* [x] Initial conversion pass
* [x] Fix link failures (properly linking to out-of-document things)
* [x] Fix relevant Bikeshed bugs (uncovered during conversion of DOM)

Just letting y'all know, so you don't spend too much time working directly on the index.html file, or putting the effort into ReSpeccing it.  I expect this to be finished in a week, as some of the bugs the DOM conversion uncovered (which this spec is also hitting) require some decent refactoring work I'll be doing over the next several days.

**Comment by arunranga** [comment]
@tabatkins : is this done? If so, can you submit a pull request so that we can work on the bikeshedded version of the spec?

**Comment by tabatkins** [comment]
Ah, like 98% done. I can finish it up this week and submit; wasn't aware there was any work being done.

**Comment by arunranga** [comment]
Ping?

**Comment by tabatkins** [comment]
Yup, sorry for the delay. It was saved locally on my work computer, so I coudln't access it from Japan. ^_^ Now I'm on vacation for the month, but I need to grab something from the office tomorrow anyway, so I'll get the file and send it up your way soon.

**Comment by arunranga** [comment]
So, latest changes to bikeshed generate a 0KB index.html when run with the force flag. I'd like to fix a pressing bug in the FileAPI spec, and if you're 98% done with bikeshedding the spec., I'd like to work on the version you've bikeshedded. Can you fix this or punt on it saying you won't fix it?

**Comment by tabatkins** [comment]
Ahhhh, I'm a huge jerk. Yeah, I'll finish it over the weekend and put it up.

**Comment by tabatkins** [comment]
And if I don't you can assume I'm a huge jerk who won't ever do it.

**Comment by arunranga** [comment]
I believe in you, @tabatkins . Don't you quit on me.

**Comment by inexorabletash** [comment]
I super believe in you @tabatkins 

I see 2 of 3 of the issues checked above. Is the 3rd ("Fix relevant Bikeshed bugs") resolved, per the active PR that says everything is good to go?

**Comment by tabatkins** [comment]
Yeah, I put up the PR for this the weekend I said I would. ^_^

**Comment by tabatkins** [comment]
(In other words, plz merge the PR, I was done two months ago.)
