### ISSUE TITLE
Remove createFor()

### ISSUE THREAD

**Issue by annevk** [w3c/FileAPI#57]
Per https://github.com/w3c/mediacapture-main/issues/404 it's not implemented everywhere and the blob URL concept is not great anyway so we should get rid of this. Let's improve what we have, but not add more baggage.

**Comment by Ms2ger** [comment]
@annevk does anything else use the "global script clean-up jobs list"?

**Comment by annevk** [comment]
Not that I know of, I filed https://github.com/whatwg/html/issues/2309.
