### ISSUE TITLE
"origin of a blob URL" is redundant/confusing

### ISSUE THREAD

**Issue by domenic** [w3c/FileAPI#63]
> The origin of a Blob URL
must be the same as the origin specified by the incumbent settings object at the time the method that created it was called.

This is stated as a normative statement, implying to me that blob URL's have some special origin that must be set at creation time.

However, the origin of a blob URL is instead normatively determined via [the URL Standard](https://url.spec.whatwg.org/#concept-url-origin). So this is just a statement of fact about what happens to be true according to the below algorithm, which is what creates blob URLs.

So it should be changed to a statement of fact, instead of a "must":

> The origin of a Blob URL **will** be the same as the origin specified by the incumbent settings object at the time the method that created it was called.

Furthermore, this would be much clearer if instead of defining the new term "origin of a Blob URL", it just linked the first "origin" in this sentence to https://url.spec.whatwg.org/#concept-url-origin

**Comment by mkruisselbrink** [comment]
It's definitely confusing. Unfortunately currently the way the URL standard defines the origin of a blob URL does not always return the correct value, in particular for opaque origins (see whatwg/url#127). I think what we'll end up doing is store the origin of a blob URL in the Blob URL store and then using that from the URL standard to return the correct origin. But yes, there is lots of confusing, redundant and conflicting stuff with regard to blob URLs.
