### ISSUE TITLE
Rename Blob URL to Object URL

### ISSUE THREAD

**Issue by epistemex** [w3c/FileAPI#65]
I just wanted to suggest a minor name change in the spec to avoid confusion, specifically for the term "Blob URL" (ref. [8.3 in current version](https://w3c.github.io/FileAPI/#DefinitionOfScheme)).

Since the method name, as you of course know, via the `URL` object is called `createObjectURL() `(and `revokeObjectURL()`) and takes both `Blob `or `File `objects (arguably very similar in type) that "Blob URL" be renamed to "Object URL" in the spec itself to more reflect the method name (that we sort of are stuck with as it's being used all over the place by now) as well as its somewhat variable argument type.

**Comment by annevk** [comment]
I think this is reasonable if there are indeed other types than `Blob`. `File` doesn't count since it's a subclass. We do have `MediaStream` and such I believe, but there's also some hope those can be made to no longer support this mechanism...

**Comment by mkruisselbrink** [comment]
Yeah, `MediaStream` and such might be a reason to rename the concept. But the scheme for these URLs is still going to be `blob:`, so even if the url doesn't represent a Blob, it might still make sense to just keep calling them Blob URLs.

**Comment by annevk** [comment]
Yeah, fair. That actually tells me we shouldn't change the name. The informal name of a type of URL is always after its scheme. Cannot really think of exceptions.

**Comment by epistemex** [comment]
Thanks guys for the feedback. Fair enough, it makes more sense to me as well to call it Blob URL and I frankly feel I'm nitpicking, but I also know there is already some confusion out there, which is why I brought it up (from sources such as StackOverflow, MDN etc.) as to the term itself, likely due to the method names being called *ObjectURL(). I'm not sure renaming the method names is such a good idea either since they are already in use. I'm sure it will straighten out over time though when awareness spreads. Thanks again.
