### ISSUE TITLE
Use ASCII origin in blob URLs

### ISSUE THREAD

**Issue by annevk** [w3c/FileAPI#7]
URLs are typically ASCII in final form. Creating URLs that are not ASCII in final form is bad news and would require ugly decoding and such.

**Comment by annevk** [comment]
We'll be changing this to ASCII origins in Gecko, assuming this was an oversight.

**Comment by arunranga** [comment]
This is a bug. Spec. text should reflect ascii final form.

On Thu, May 7, 2015 at 12:04 AM, Anne van Kesteren <notifications@github.com
