### ISSUE TITLE
where is this document for "utils.regexp.isChinese"?

### ISSUE THREAD

**Issue by anlexN** [w3c/FileAPI#70]
where is this document for "utils.regexp.isChinese"?
![default](https://cloud.githubusercontent.com/assets/8686739/23058822/b22569dc-f531-11e6-8fd2-c62bc25ecb1e.PNG)

**Comment by inexorabletash** [comment]
Yeah, the example should probably just have comments about using the data there, or at most reference a generic `processFileContent(fileString)` rather than implying some library.

**Comment by anlexN** [comment]
@inexorabletash , library? what library??????

**Comment by anlexN** [comment]
@mkruisselbrink , could you please tell me why? i need your hand!

**Comment by anlexN** [comment]
@inexorabletash @sgraham @dglazkov @hober ,could you please tell me why? i need your hand!

**Comment by annevk** [comment]
@anlexN this is made up code. There is no library. utils.regexp.isChinese does not exist.

**Comment by anlexN** [comment]
@annevk ， i hear from your github's account that you are from W3C . Such that , it make me puzzled that utils.regexp.isChinese does not exist. 
"FileAPI" document , those authores, how do you write this code? where is complete code?

**Comment by annevk** [comment]
As I said up, made up, it's a fictional example.

**Comment by anlexN** [comment]
As i google that, JAVA api has relationship about "isChinese", but Ecamascript specification don't tell about that. I'm silly about that.
Could you tell me how to realize this feature using pure ecamascript?

**Comment by anlexN** [comment]
i think , one idea, judge chinese unicode range......
@mkruisselbrink , why do you come in? do you leave the earth?

**Comment by anlexN** [comment]
@vsesh ,could you express an opinion to me?

**Comment by vsesh** [comment]
@anlexN You got an answer. It's just a example of code. If the method has existed, it would not have been implemented as part of this spec.

**Comment by anlexN** [comment]
Thank you, @vsesh ! But could you recommend me some api about this implementation?  if you know.

**Comment by vsesh** [comment]
Sorry, but i don't know. I think this spec doesn't exists becouse it sounds like specific task.

**Comment by anlexN** [comment]
you are sincere men , @vsesh @annevk @inexorabletash ! i hopefully make friend with you.
