### ISSUE TITLE
What should happen when you load a blob URL in an iframe?

### ISSUE THREAD

**Issue by dbates-wk** [w3c/FileAPI#82]
Subsection [Response Headers](https://w3c.github.io/FileAPI/#processing-media-types) of section [Dereferencing Model for Blob URLs](https://w3c.github.io/FileAPI/#requestResponseModel) of File API does not describe what to do when dereferencing a Blob URL that was constructed from raw data and does not have a type. What should we do?

**Example**

Open a page with the following markup:

```
<!DOCTYPE html>
<html>
<body>
<script>
var frame = document.createElement("iframe");
frame.src = URL.createObjectURL(new Blob(["<h1>Hello</h1>"]));
document.body.appendChild(frame)
</script>
</body>
</html>
```

What should happen?

Here is what various browsers do:

Browser        |  Observed behavior
------------ | -------------
Chrome Canary for Mac 61.0.3115.0 (Official Build) canary (64-bit) | Shows an iframe with `<h1>Hello</h1>` (verbatim) (i.e. renders content as plain text)
Firefox for Mac 53.0.3 (64-bit) | Shows an iframe with <h1>Hello</h1> (rendered as HTML)
Safari 10.1 (12603.1.24) | Downloads the contents associated with the blob URL to a file named "unknown"
Edge 38.14393.1066.0 (EdgeHTML 14.14393) | Shows an empty iframe
Internet Explorer 11 (11.1198.14393.0) | Shows an empty iframe

**Additional remarks:**

For comparison, modify the above example to construct the Blob with type "text/html" and open this page:

```
<!DOCTYPE html>
<html>
<body>
<script>
var frame = document.createElement("iframe");
frame.src = URL.createObjectURL(new Blob(["<h1>Hello</h1>"], {type: "text/html"}));
document.body.appendChild(frame)
</script>
</body>
</html>
```

Here is what the above browsers do:

Browser        |  Observed behavior
------------ | -------------
Chrome Canary for Mac 61.0.3115.0 (Official Build) canary (64-bit) | Shows an iframe with <h1>Hello</h1> (rendered as HTML)
Firefox for Mac 53.0.3 (64-bit) | Shows an iframe with <h1>Hello</h1> (rendered as HTML)
Safari 10.1 (12603.1.24) | Shows an iframe with <h1>Hello</h1> (rendered as HTML)
Edge 38.14393.1066.0 (EdgeHTML 14.14393) | Shows an empty iframe
Internet Explorer 11 (11.1198.14393.0) | Shows an empty iframe

**Comment by dbates-wk** [comment]
CC @arunranga @mkruisselbrink @bzbarsky @hober @annevk

**Comment by domenic** [comment]
Note that that section is informative and delegates to the URL/Fetch spec.

My reading of the normative text is that this goes from

- https://html.spec.whatwg.org/#navigate ->
- https://html.spec.whatwg.org/#process-a-navigate-fetch -> 
- https://fetch.spec.whatwg.org/#concept-fetch ->
- https://fetch.spec.whatwg.org/#concept-main-fetch ->
- https://fetch.spec.whatwg.org/#concept-scheme-fetch

which gives you the information you want (Content-Length and Content-Type headers, as well as body).

To me it looks like Chrome has this consistently right.

**Comment by domenic** [comment]
Wait, I got that last part wrong; I'm no longer convinced Chrome is consistently right.

What is the `type` attribute value for `new Blob(["<h1>Hello</h1>"])`? The spec isn't very clear. In any case, the Content-Type header will have that value (possibly the empty string), which causes consequences.

**Comment by domenic** [comment]
OK, so it looks like at least some browsers give an empty string `type`, and thus per spec an empty-string `Content-Type`. That lands us in step 7 of https://html.spec.whatwg.org/#process-a-navigate-response:

> Otherwise, the document's type is such that the resource will not affect browsingContext, e.g., because the resource is to be handed to an external application or because it is an unknown type that will be processed as a download. Process the resource appropriately.

So it seems the spec is kind of assuming that empty-string content-type files should be downloaded. I'm not sure that's accurate in all browsers, but that at least seems to align with your Safari test results; maybe someone should also set up a standalone page that serves itself with a `Content-Type: ` header and see what happens.

**Comment by bzbarsky** [comment]
Seems to me like this should be a response with

    Content-Type:

as currently written in the specs linked, because the `type` for a Blob with no type provided is `""`.

So then we land in https://html.spec.whatwg.org/#process-a-navigate-fetch and go off to https://mimesniff.spec.whatwg.org/#computed-mime-type which is not really written on top of the fetch concept of Responses so it's hard to tell what's going on here.  But if we assume that https://mimesniff.spec.whatwg.org/#supplied-mime-type-detection-algorithm step 4 applies, we get an empty supplied-type, which is not a "parsable MIME type" and hence we use undefined as the supplied type.

So then we're back in https://mimesniff.spec.whatwg.org/#mime-type-sniffing-algorithm (which got called by https://mimesniff.spec.whatwg.org/#computed-mime-type which is called by https://html.spec.whatwg.org/#process-a-navigate-response step 4; note that this is before the step 7 quoted above).  This says to do

> https://mimesniff.spec.whatwg.org/#rules-for-identifying-an-unknown-mime-type with the sniff-scriptable flag equal to the inverse of the no-sniff flag

and what that does _really_ depends on what the sniff-scriptable flag is set to.  If that flag is set to true, then anything starting with `"<h1"` gets sniffed as `"text/html"`, per that table.  If it's set to false, then we end up in step 9 and get `"text/plain"` in this case.

**Comment by bzbarsky** [comment]
Oh, and I see no mention of the no-sniff thing in HTML or fetch.

I agree that the right test for this is what UAs do with an HTTP response without a content-type header (and ideally no extension in the URL, just to be sure).  That should be consistent with the blob behavior, but may also not be interoperable across UAs.

In either case, either the Chrome or the Firefox behavior is correct here, depending on that no-sniff flag thing.

**Comment by domenic** [comment]
Thanks, my eyes completely glossed over the "Let type be the computed type of response." step. @bzbarsky's analysis is more correct than mine.

**Comment by dbates-wk** [comment]
Filed <https://bugs.webkit.org/show_bug.cgi?id=172873> towards implementing support for content sniffing in WebKit. Closing issue.
