### ISSUE TITLE
Update the WD

### ISSUE THREAD

**Issue by LJWatson** [w3c/FileAPI#86]
@mkruisselbrink and @vsesh, could you stage an update to the WD possibly? It hasn't been updated in too long. Thanks.

**Comment by mkruisselbrink** [comment]
What is needed to do so? (sorry, I haven't really dealt with w3c publishing processes before).

**Comment by plehegar** [comment]
@mkruisselbrink , based on the changes from the pull request, I requested a publication of the draft for tomorrow. So, I believe we should be all set. I'll add this draft to pile of bikeshed documents that needs to use automatic publishing.

**Comment by plehegar** [comment]
https://www.w3.org/TR/2017/WD-FileAPI-20171026/
