### ISSUE TITLE
Rename EndingTypes to EndingType or EndingsType

### ISSUE THREAD

**Issue by inexorabletash** [w3c/FileAPI#91]
Sorry, missed this during the review.

The `EndingTypes` enum is named with a plural which doesn't make sense when used in the dictionary:
```webidl
dictionary BlobPropertyBag {
  DOMString type = "";
  EndingTypes endings = "transparent";
};
```
There's only one _type_ so the property type shouldn't be _types_. 

Either `EndingType` or `EndingsType` makes more sense.

**Comment by mkruisselbrink** [comment]
Ah yes. I shouldn't have blindly copied the old spec. Either sounds good to me.
